---
datacenter:
  children:
    switches:
      hosts:
        172.16.105.3[1:9]:
      vars:
        testVar: 999
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_ssh_pass: Admin@123
    ansible_become_password: Admin@123
