---
datacenter:
  children:
    routers:
      hosts:
        172.16.105.3[1:9]:
      vars:
        testVar: 999
    switches:
      hosts:
      172.16..105.31:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_ssh_pass: Admin@123
